### ISSUE TITLE
wasmbuild error

### ISSUE THREAD

**Issue by jingslunt** [denoland/wasmbuild#76]
>deno.json
```
{
    "tasks": {
      "wasmbuild": "deno run -A https://deno.land/x/wasmbuild/main.ts"
    }
  }
```

> deno task wasmbuild
```
Task wasmbuild deno run -A https://deno.land/x/wasmbuild/main.ts
Warning Implicitly using latest version (0.11.0) for https://deno.land/x/wasmbuild/main.ts
error: Uncaught (in promise) Error: There were multiple cdylib crates in the repo. Please select one by providing the '-p <crate-name>' cli flag.

 * wasmbuild
 * deno_test
      throw new Error(
            ^
    at CargoWorkspace.getWasmCrate (https://deno.land/x/wasmbuild@0.11.0/lib/manifest.ts:81:13)
    at runPreBuild (https://deno.land/x/wasmbuild@0.11.0/lib/pre_build.ts:24:27)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async runBuildCommand (https://deno.land/x/wasmbuild@0.11.0/lib/commands/build_command.ts:9:18)
    at async https://deno.land/x/wasmbuild@0.11.0/main.ts:22:5
```

**Comment by dsherret** [comment]
Do either...

```
deno run -A https://deno.land/x/wasmbuild/main.ts -p wasmbuild
# or
deno run -A https://deno.land/x/wasmbuild/main.ts -p deno_test
```

...to select wich cargo project to build.

**Comment by jingslunt** [comment]
it works,thx
